create extension if not exists "hypopg" with schema "extensions";

create extension if not exists "index_advisor" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."archived_order_items" (
    "id" bigint generated always as identity not null,
    "parent_order_id" bigint not null,
    "original_item_id" bigint not null,
    "deletion_batch_id" uuid default gen_random_uuid(),
    "item_data" jsonb not null,
    "reason" text,
    "deleted_at" timestamp with time zone default now(),
    "deleted_by" text not null
      );


alter table "public"."archived_order_items" enable row level security;


  create table "public"."archived_orders" (
    "id" bigint generated always as identity not null,
    "order_data" jsonb not null,
    "reason" text,
    "deleted_at" timestamp with time zone default now(),
    "deleted_by" text not null,
    "original_order_id" uuid
      );


alter table "public"."archived_orders" enable row level security;


  create table "public"."order_items" (
    "id" uuid not null default gen_random_uuid(),
    "order_id" uuid not null,
    "product_id" uuid not null,
    "quantity" integer not null default 1,
    "price_at_purchase" numeric(12,2) not null,
    "created_at" timestamp with time zone not null default now(),
    "note" text,
    "is_prepared" boolean default false
      );


alter table "public"."order_items" enable row level security;


  create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "table_number" text,
    "notes" text,
    "status" text not null default 'pending'::text,
    "total_amount" numeric(12,2) not null default 0.00,
    "created_at" timestamp with time zone not null default now(),
    "daily_order_number" integer,
    "is_paid" boolean default false
      );


alter table "public"."orders" enable row level security;


  create table "public"."products" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "slug" text not null,
    "category" text not null,
    "images" text[] not null,
    "brand" text not null,
    "description" text not null,
    "price" numeric(12,2) not null default 0,
    "stock" integer not null default 0,
    "rating" numeric(3,2) not null default 0,
    "num_reviews" integer not null default 0,
    "is_featured" boolean default false,
    "banner" text,
    "created_at" timestamp with time zone not null default now(),
    "avaliable" boolean
      );


alter table "public"."products" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "role" text default 'client'::text
      );



  create table "public"."views" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
      );


alter table "public"."views" enable row level security;

CREATE UNIQUE INDEX archived_order_items_pkey ON public.archived_order_items USING btree (id);

CREATE UNIQUE INDEX archived_orders_pkey ON public.archived_orders USING btree (id);

CREATE INDEX idx_archived_items_order ON public.archived_order_items USING btree (parent_order_id);

CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);

CREATE INDEX idx_orders_status ON public.orders USING btree (status);

CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX views_pkey ON public.views USING btree (id);

alter table "public"."archived_order_items" add constraint "archived_order_items_pkey" PRIMARY KEY using index "archived_order_items_pkey";

alter table "public"."archived_orders" add constraint "archived_orders_pkey" PRIMARY KEY using index "archived_orders_pkey";

alter table "public"."order_items" add constraint "order_items_pkey" PRIMARY KEY using index "order_items_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."views" add constraint "views_pkey" PRIMARY KEY using index "views_pkey";

alter table "public"."order_items" add constraint "order_items_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE not valid;

alter table "public"."order_items" validate constraint "order_items_order_id_fkey";

alter table "public"."order_items" add constraint "order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT not valid;

alter table "public"."order_items" validate constraint "order_items_product_id_fkey";

alter table "public"."order_items" add constraint "order_items_quantity_check" CHECK ((quantity > 0)) not valid;

alter table "public"."order_items" validate constraint "order_items_quantity_check";

alter table "public"."orders" add constraint "orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'brewing'::text, 'ready'::text, 'completed'::text, 'cancelled'::text]))) not valid;

alter table "public"."orders" validate constraint "orders_status_check";

alter table "public"."orders" add constraint "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL not valid;

alter table "public"."orders" validate constraint "orders_user_id_fkey";

alter table "public"."products" add constraint "products_category_check" CHECK ((category = ANY (ARRAY['food'::text, 'drinks'::text, 'smoke'::text]))) not valid;

alter table "public"."products" validate constraint "products_category_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'worker'::text, 'client'::text]))) not valid;

alter table "public"."profiles" validate constraint "profiles_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_to_table_ticket(p_table_number text, p_items jsonb, p_total_amount numeric)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
  v_order_id uuid;
begin
  -- 1. Find an existing unpaid order for this table
  select id into v_order_id
  from orders
  where table_number = p_table_number
  and is_paid = false
  limit 1;

  -- 2. If no order found, create one
  if v_order_id is null then
    insert into orders (table_number, total_amount, is_paid, status)
    values (p_table_number, p_total_amount, false, 'pending')
    returning id into v_order_id;
  else
    -- 3. If order exists, update total
    update orders
    set total_amount = total_amount + p_total_amount,
        status = 'pending' -- Keep the order active in kitchen
    where id = v_order_id;
  end if;

  -- 4. Insert new items linked to the (new or existing) order
  insert into order_items (order_id, product_id, quantity, price_at_purchase, note)
  select 
    v_order_id, 
    (item->>'product_id')::uuid, 
    (item->>'quantity')::int, 
    (item->>'price_at_purchase')::numeric,
    item->>'note'
  from jsonb_array_elements(p_items) as item;
  
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'client'); -- Defaults everyone to 'client'
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_daily_order_number()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$DECLARE
  next_num INTEGER;
BEGIN
  -- Get the max number for today, or start at 1
  SELECT COALESCE(MAX(daily_order_number), 999) + 1 
  INTO next_num
  FROM public.orders
  WHERE DATE(created_at) = CURRENT_DATE;
  
  NEW.daily_order_number := next_num;
  RETURN NEW;
END;$function$
;

grant delete on table "public"."archived_order_items" to "anon";

grant insert on table "public"."archived_order_items" to "anon";

grant references on table "public"."archived_order_items" to "anon";

grant select on table "public"."archived_order_items" to "anon";

grant trigger on table "public"."archived_order_items" to "anon";

grant truncate on table "public"."archived_order_items" to "anon";

grant update on table "public"."archived_order_items" to "anon";

grant delete on table "public"."archived_order_items" to "authenticated";

grant insert on table "public"."archived_order_items" to "authenticated";

grant references on table "public"."archived_order_items" to "authenticated";

grant select on table "public"."archived_order_items" to "authenticated";

grant trigger on table "public"."archived_order_items" to "authenticated";

grant truncate on table "public"."archived_order_items" to "authenticated";

grant update on table "public"."archived_order_items" to "authenticated";

grant delete on table "public"."archived_order_items" to "service_role";

grant insert on table "public"."archived_order_items" to "service_role";

grant references on table "public"."archived_order_items" to "service_role";

grant select on table "public"."archived_order_items" to "service_role";

grant trigger on table "public"."archived_order_items" to "service_role";

grant truncate on table "public"."archived_order_items" to "service_role";

grant update on table "public"."archived_order_items" to "service_role";

grant delete on table "public"."archived_orders" to "anon";

grant insert on table "public"."archived_orders" to "anon";

grant references on table "public"."archived_orders" to "anon";

grant select on table "public"."archived_orders" to "anon";

grant trigger on table "public"."archived_orders" to "anon";

grant truncate on table "public"."archived_orders" to "anon";

grant update on table "public"."archived_orders" to "anon";

grant delete on table "public"."archived_orders" to "authenticated";

grant insert on table "public"."archived_orders" to "authenticated";

grant references on table "public"."archived_orders" to "authenticated";

grant select on table "public"."archived_orders" to "authenticated";

grant trigger on table "public"."archived_orders" to "authenticated";

grant truncate on table "public"."archived_orders" to "authenticated";

grant update on table "public"."archived_orders" to "authenticated";

grant delete on table "public"."archived_orders" to "service_role";

grant insert on table "public"."archived_orders" to "service_role";

grant references on table "public"."archived_orders" to "service_role";

grant select on table "public"."archived_orders" to "service_role";

grant trigger on table "public"."archived_orders" to "service_role";

grant truncate on table "public"."archived_orders" to "service_role";

grant update on table "public"."archived_orders" to "service_role";

grant delete on table "public"."order_items" to "anon";

grant insert on table "public"."order_items" to "anon";

grant references on table "public"."order_items" to "anon";

grant select on table "public"."order_items" to "anon";

grant trigger on table "public"."order_items" to "anon";

grant truncate on table "public"."order_items" to "anon";

grant update on table "public"."order_items" to "anon";

grant delete on table "public"."order_items" to "authenticated";

grant insert on table "public"."order_items" to "authenticated";

grant references on table "public"."order_items" to "authenticated";

grant select on table "public"."order_items" to "authenticated";

grant trigger on table "public"."order_items" to "authenticated";

grant truncate on table "public"."order_items" to "authenticated";

grant update on table "public"."order_items" to "authenticated";

grant delete on table "public"."order_items" to "service_role";

grant insert on table "public"."order_items" to "service_role";

grant references on table "public"."order_items" to "service_role";

grant select on table "public"."order_items" to "service_role";

grant trigger on table "public"."order_items" to "service_role";

grant truncate on table "public"."order_items" to "service_role";

grant update on table "public"."order_items" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."views" to "anon";

grant insert on table "public"."views" to "anon";

grant references on table "public"."views" to "anon";

grant select on table "public"."views" to "anon";

grant trigger on table "public"."views" to "anon";

grant truncate on table "public"."views" to "anon";

grant update on table "public"."views" to "anon";

grant delete on table "public"."views" to "authenticated";

grant insert on table "public"."views" to "authenticated";

grant references on table "public"."views" to "authenticated";

grant select on table "public"."views" to "authenticated";

grant trigger on table "public"."views" to "authenticated";

grant truncate on table "public"."views" to "authenticated";

grant update on table "public"."views" to "authenticated";

grant delete on table "public"."views" to "service_role";

grant insert on table "public"."views" to "service_role";

grant references on table "public"."views" to "service_role";

grant select on table "public"."views" to "service_role";

grant trigger on table "public"."views" to "service_role";

grant truncate on table "public"."views" to "service_role";

grant update on table "public"."views" to "service_role";


  create policy "Allow authenticated full access"
  on "public"."order_items"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Allow authenticated full access"
  on "public"."orders"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



  create policy "Allow admins to insert products"
  on "public"."products"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "Allow authenticated users to update products"
  on "public"."products"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Allow public read access"
  on "public"."products"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can update all profiles"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT profiles_1.role
   FROM public.profiles profiles_1
  WHERE (profiles_1.id = auth.uid())) = 'admin'::text));



  create policy "Admins can view all profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((( SELECT profiles_1.role
   FROM public.profiles profiles_1
  WHERE (profiles_1.id = auth.uid())) = 'admin'::text));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "anon access"
  on "public"."views"
  as permissive
  for insert
  to anon
with check (true);


CREATE TRIGGER trigger_set_daily_order_number BEFORE INSERT ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_daily_order_number();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow authenticated updates"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'product-images'::text));



  create policy "Allow authenticated uploads"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'product-images'::text));



